<a href="https://colab.research.google.com/github/nazlicanalagoz/DataScience_Uni/blob/main/2_numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# kurulu bir paketin versiyonu
np.__version__

'1.19.5'

In [ ]:
# modüle ait fonksiyonları listeleme
dir(np)

In [ ]:
# bir fonksiyonun çalışması hakkında bilgi verir
np.abs?

In [ ]:
# dizi oluşturma
dizi = np.array([2,4,6,8])
dizi

array([2, 4, 6, 8])

In [ ]:
# matris oluşturma
matris = np.array([[1,2,3],[4,5,6],[7,8,9]])
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# liste oluşturma
liste = [1,3,5,7,9]
liste

[1, 3, 5, 7, 9]

In [ ]:
# array fonksiyonu ile listeyi diziye dönüştürme
listedendizi = np.array(liste)
listedendizi

array([1, 3, 5, 7, 9])

In [ ]:
# arange metodu ile dizi oluşturma (başlangıç,bitiş,adım sayısı) bitiş dahil değil
dizi1 = np.arange(1,10,2)
dizi1

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
azalandizi = np.arange(10,1,-1)
azalandizi  #tek boyutlu dizi yani vektördür

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
# var olan bir diziyi yapılandırma
d = np.arange(10).reshape(5,2) #5x2 lik matris yaptı (sözlü sorar)
d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# linspace ile dizi oluşturma
np.linspace(0,10,20) # 0-10 arasını 20 eşit parçaya böler

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

**Özel Dizi ya da Matris oluşturma**

In [ ]:
# sıfır dizi ya da matris oluşturma
sifir = np.zeros(5)
sifir

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(shape=(3,2)) # 3x2lik bir 0 matrisi

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# birim matris oluşturma
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# verilen değerden oluşan bir matris oluşturma
np.full(shape=(3,4),fill_value=7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

**Rastgele Sayı İşlemler**



In [ ]:
np.random.randint(1,10,4)  # 1 ile 10 arasında rastgele 4 tane tam sayı getirir

array([9, 5, 4, 1])

In [ ]:
# 0 ile 1 arasında rastgele 5 sayı oluşturalım
np.random.rand(5)

array([0.83261985, 0.77815675, 0.87001215, 0.97861834, 0.79915856])

In [ ]:
# 0 ile 100 arasında (100 dahil) 1 adet tam sayı üreten kod satırı
np.random.randint(0,101,1)

array([29])

In [ ]:
# herkeste aynı rastgele değeri oluşturmasını istiyoruz
np.random.seed(22) # ortak bi proje yürütülüyorsa herkeste aynı sayı gözüksün diye kullanılır
np.random.randint(0,101,1)

array([4])

In [ ]:
m2 = np.random.randint(100,size=(3,4))
m2

array([[44, 64, 84,  8],
       [95, 93, 18, 14],
       [45, 88, 93, 39]])

In [ ]:
d5 = np.random.randint(1,100,6)
d5

array([35, 42,  9, 41,  6, 28])

In [ ]:
# indeks
d5[0]

35

In [ ]:
#son elemean
d5[5]

28

In [ ]:
# son eleman 2.seçenek
d5[-1]

28

In [ ]:
# matriste indeksleme
m2[0,0]    # 0.satır 0.sütun

44

In [ ]:
d5

array([35, 42,  9, 41,  6, 28])

In [ ]:
# dilimleme
d5[1:3] # 1 indisli elemandan 4 indisli elemana kadar alır (4 dahil değil)

array([42,  9])

In [ ]:
d5[:2]   # başlangıçtan belirtilen değere kadar alır

array([35, 42])

**Matriste Dilimleme**

In [ ]:
m2

array([[44, 64, 84,  8],
       [95, 93, 18, 14],
       [45, 88, 93, 39]])

In [ ]:
sutun1 = m2[:,2:3] # 1.sütundan başlayıp 2.sütuna kadar al  (soru sorulacak)
sutun1

array([84, 18, 93])

In [ ]:
# dizinin ya da matrisin boyutunu bulma
m2.ndim  # 1 dönerse dizi(tek boyutlu), 2 dönerse matris

2

In [ ]:
d5

array([35, 42,  9, 41,  6, 28])

In [ ]:
d5.ndim

1

In [ ]:
# matrisin satır ve sütun sayısını öğrenme
m2.shape

(3, 4)

In [ ]:
# matrisin transpozesini almak
m2

array([[44, 64, 84,  8],
       [95, 93, 18, 14],
       [45, 88, 93, 39]])

In [ ]:
m2.T

array([[44, 95, 45],
       [64, 93, 88],
       [84, 18, 93],
       [ 8, 14, 39]])

In [ ]:
# dizi ve matrisler üzerinde matematiksel işlemler
A = np.array([[1,2],[3,4]])
B = A
B

array([[1, 2],
       [3, 4]])

In [ ]:
# matrislerde toplama
C = A+B
C

array([[2, 4],
       [6, 8]])

In [ ]:
np.add(A,B)

array([[2, 4],
       [6, 8]])

In [ ]:
# matrislerde çarpma
D= np.dot(A,B)
D

array([[ 7, 10],
       [15, 22]])

In [ ]:
# matrislerde çıkarma
A-B

array([[0, 0],
       [0, 0]])

NP İle İstatistiksel İşlemler

In [ ]:
np.random.seed(0)
ras = np.random.randint(1,100,10)
ras

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [ ]:
# minimum değeri bulma
ras.min()

10

In [ ]:
# max değeri
ras.max()

88

In [ ]:
# aritmetik ortalama
ras.mean()

53.5

In [ ]:
# dizi elemanlarının toplamı
ras.sum()

535

In [ ]:
# standart sapma
ras.std()

24.3567239176372

In [ ]:
# varyant bulma
ras.var()

593.25

In [ ]:
# küçükten büyüğe sıralama
ras.sort()
ras

array([10, 22, 37, 45, 48, 65, 68, 68, 84, 88])

In [ ]:
# axis 1 ise satırları, axis 0 ise sütunları toplar
m2.sum(axis=1)

array([200, 220, 265])

In [ ]:
# ras dizisinden 45ten büyük elemanları verir
ras[ras>45]

array([48, 65, 68, 68, 84, 88])

In [ ]:
np.sum(ras[ras>45]) # 45 ten büyük elemanlarının toplamı

421